sonar.organization=leop250
sonar.projectKey=Leop250_Projet_Scribe

sonar.sources=backend,frontend/src
sonar.tests=backend/unit_testing
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/venv/**,backend/alembic/versions/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
